// test/seo.test.mjs — SEO + structural integrity checks for index.html.
//
// These don't render the page; they grep the source for tags
// and call buildStructuredData() from filter.mjs to verify the
// JSON-LD. The point is to fail PR CI the moment someone removes
// a meta tag, a JSON-LD field, the skip link, the h1, or any of
// the other bits that make the page discoverable / navigable /
// accessible. The user explicitly asked for SEO optimization and
// UI/UX polish — this test pins the deliverables.

import { test } from "node:test";
import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { buildStructuredData } from "../filter.mjs";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const indexHtml = readFileSync(resolve(REPO, "index.html"), "utf8");
const menu = JSON.parse(readFileSync(resolve(REPO, "data/menu.json"), "utf8"));

// ---------------------------------------------------------------------------
// 1) <head> — meta tags, OG, Twitter Card, canonical, theme-color
// ---------------------------------------------------------------------------

test("meta: description exists and is between 50–200 chars", () => {
  const m = indexHtml.match(/<meta name="description" content="([^"]+)">/u);
  assert.ok(m, "missing meta description");
  assert.ok(m[1].length >= 50 && m[1].length <= 200, `length=${m[1].length}`);
  assert.match(m[1], /Waffle House/i);
});

test("meta: keywords present", () => {
  assert.match(indexHtml, /<meta name="keywords" content="[^"]*menu[^"]*"[^>]*>/u);
});

test("meta: robots allows indexing", () => {
  const m = indexHtml.match(/<meta name="robots" content="([^"]+)">/u);
  assert.ok(m, "missing robots meta");
  assert.match(m[1], /index/u);
});

test("meta: theme-color present (light + dark)", () => {
  const light = indexHtml.match(/<meta name="theme-color" content="([^"]+)" media="\(prefers-color-scheme: light\)">/u);
  const dark = indexHtml.match(/<meta name="theme-color" content="([^"]+)" media="\(prefers-color-scheme: dark\)">/u);
  assert.ok(light, "missing light theme-color");
  assert.ok(dark, "missing dark theme-color");
});

test("canonical: points to wafflestats.com", () => {
  const m = indexHtml.match(/<link rel="canonical" href="([^"]+)">/u);
  assert.ok(m, "missing canonical link");
  assert.equal(m[1], "https://wafflestats.com/");
});

test("Open Graph: og:title, og:description, og:url, og:type, og:site_name", () => {
  for (const k of ["og:title", "og:description", "og:url", "og:type", "og:site_name"]) {
    const re = new RegExp(`<meta property="${k}" content="[^"]+"[^>]*>`, "u");
    assert.match(indexHtml, re, `missing Open Graph ${k}`);
  }
});

test("Twitter Card: twitter:card, twitter:title, twitter:description", () => {
  for (const k of ["twitter:card", "twitter:title", "twitter:description"]) {
    const re = new RegExp(`<meta name="${k}" content="[^"]+"[^>]*>`, "u");
    assert.match(indexHtml, re, `missing Twitter ${k}`);
  }
});

test("lang: <html lang=\"en\"> for screen readers + a11y tree", () => {
  assert.match(indexHtml, /<html lang="en">/u);
});

// ---------------------------------------------------------------------------
// 2) JSON-LD structured data — WebSite + Menu schema
//    Generated by buildStructuredData() in filter.mjs, the same
//    module the page imports. Tests call the function directly so
//    we don't need a JSDOM roundtrip.
// ---------------------------------------------------------------------------

test("JSON-LD: buildStructuredData returns [WebSite, Menu]", () => {
  const blocks = buildStructuredData(menu);
  assert.equal(blocks.length, 2);
  assert.equal(blocks[0]["@type"], "WebSite");
  assert.equal(blocks[1]["@type"], "Menu");
});

test("JSON-LD: WebSite schema has name + url", () => {
  const [website] = buildStructuredData(menu);
  assert.equal(website["@context"], "https://schema.org");
  assert.equal(website["@type"], "WebSite");
  assert.equal(website.url, "https://wafflestats.com/");
  assert.ok(website.name);
});

test("JSON-LD: Menu schema has hasMenuSection per data section", () => {
  const [, menuLd] = buildStructuredData(menu);
  assert.equal(menuLd["@type"], "Menu");
  assert.equal(menuLd.inLanguage, "en");
  assert.ok(Array.isArray(menuLd.hasMenuSection));
  assert.equal(menuLd.hasMenuSection.length, menu.sections.length,
    `Menu schema should have ${menu.sections.length} sections, got ${menuLd.hasMenuSection.length}`);
});

test("JSON-LD: every MenuSection has at least one MenuItem", () => {
  const [, menuLd] = buildStructuredData(menu);
  for (const sec of menuLd.hasMenuSection) {
    assert.ok(sec.name, "section name missing");
    assert.ok(Array.isArray(sec.hasMenuItem) && sec.hasMenuItem.length > 0,
      `section "${sec.name}" has no menu items`);
  }
});

test("JSON-LD: MenuItem has nutrition + calories string", () => {
  const [, menuLd] = buildStructuredData(menu);
  let checked = 0;
  for (const sec of menuLd.hasMenuSection) {
    for (const it of sec.hasMenuItem) {
      assert.ok(it.name, "MenuItem name missing");
      assert.ok(it.nutrition, `MenuItem "${it.name}" has no nutrition`);
      assert.ok(typeof it.nutrition.calories === "string",
        `MenuItem "${it.name}" calories not a string`);
      checked++;
    }
  }
  assert.ok(checked >= 50, `expected to check at least 50 items, checked ${checked}`);
});

test("JSON-LD: every MenuItem name matches a real menu item", () => {
  // Pins that the structured data stays in sync with the data:
  // if someone drops a section, the schema count test above fails
  // first; this test catches a typo in item names.
  const [, menuLd] = buildStructuredData(menu);
  const realNames = new Set(
    menu.sections.flatMap(s => s.groups.flatMap(g => g.items.map(i => i.n)))
  );
  let mismatched = 0;
  for (const sec of menuLd.hasMenuSection) {
    for (const it of sec.hasMenuItem) {
      if (!realNames.has(it.name)) mismatched++;
    }
  }
  assert.equal(mismatched, 0, `${mismatched} MenuItem names don't match data`);
});

test("JSON-LD: the page wires it up (call to buildStructuredData + script injection)", () => {
  // The function is imported and injectStructuredData() walks the
  // return value and appends <script type="application/ld+json">.
  assert.match(indexHtml, /buildStructuredData\(data\)/u);
  assert.match(indexHtml, /application\/ld\+json/u);
});

// ---------------------------------------------------------------------------
// 3) Accessibility — skip link, h1, aria-live, focus
// ---------------------------------------------------------------------------

test("a11y: skip-to-content link is the first interactive element", () => {
  const m = indexHtml.match(/<a class="skip" href="#menu">[^<]*<\/a>/u);
  assert.ok(m, "missing skip link");
  const skipPos = indexHtml.indexOf(m[0]);
  const mainPos = indexHtml.indexOf("<main");
  assert.ok(skipPos < mainPos, "skip link must appear before <main>");
});

test("a11y: exactly one h1 (the visually-hidden one in the header)", () => {
  const h1Opens = indexHtml.match(/<h1\b[^>]*>/gu) || [];
  assert.equal(h1Opens.length, 1, `expected exactly 1 <h1>, found ${h1Opens.length}`);
  assert.match(h1Opens[0], /<h1 class="visually-hidden">/u,
    "h1 should be visually hidden so the sign header remains the visual title");
});

test("a11y: <main> has id=\"menu\" (skip link target)", () => {
  assert.match(indexHtml, /<main id="menu"/u);
});

test("a11y: search input labelled", () => {
  const m = indexHtml.match(/<input id="q"[^>]*aria-label="[^"]+"/u);
  assert.ok(m, "search input must have aria-label");
});

test("a11y: filter chips group has accessible name", () => {
  assert.match(indexHtml, /<div class="chips"[^>]*aria-label="[^"]+"/u);
});

test("a11y: avoidBanner is aria-live so SR users hear filter changes", () => {
  assert.match(indexHtml, /<div class="banner"[^>]*aria-live="polite"/u);
});

test("a11y: empty state is aria-live", () => {
  assert.match(indexHtml, /<div class="empty"[^>]*aria-live="polite"/u);
});

// ---------------------------------------------------------------------------
// 4) UI controls — clear-all, jump-nav, back-to-top, keyboard hints
// ---------------------------------------------------------------------------

test("UI: clear-all button exists with hidden by default", () => {
  assert.match(indexHtml, /<button[^>]*id="clearAll"[^>]*hidden/u);
});

test("UI: quick-jump nav exists with aria-label", () => {
  assert.match(indexHtml, /<nav class="jumpnav"[^>]*aria-label="[^"]+"/u);
});

test("UI: back-to-top button exists with hidden by default", () => {
  assert.match(indexHtml, /<button[^>]*id="totop"[^>]*hidden/u);
});

test("UI: keyboard hint \"/\" rendered in the search input", () => {
  assert.match(indexHtml, /<kbd class="search-hint"[^>]*>\/<\/kbd>/u);
});

// ---------------------------------------------------------------------------
// 5) Render — every section gets a unique id (jump-nav target)
// ---------------------------------------------------------------------------

test("render: every section gets a unique id like sec-<slug>", () => {
  assert.match(indexHtml, /<details class="sec" id="sec-\$\{esc\(/u);
});

// ---------------------------------------------------------------------------
// 6) Performance / preloading
// ---------------------------------------------------------------------------

test("perf: data/menu.js is preloaded", () => {
  assert.match(indexHtml, /<link rel="preload"[^>]+href="data\/menu\.js"/u);
});

test("perf: filter.mjs is modulepreloaded", () => {
  assert.match(indexHtml, /<link rel="modulepreload"[^>]+href="filter\.mjs"/u);
});

test("perf: fonts preconnect (no render-blocking DNS lookups)", () => {
  assert.match(indexHtml, /<link rel="preconnect"[^>]+fonts\.googleapis\.com/u);
  assert.match(indexHtml, /<link rel="preconnect"[^>]+fonts\.gstatic\.com[^>]+crossorigin/u);
});

// ---------------------------------------------------------------------------
// 7) Print + reduced motion + dark mode
// ---------------------------------------------------------------------------

test("a11y: prefers-reduced-motion respected", () => {
  assert.match(indexHtml, /@media \(prefers-reduced-motion:reduce\)/u);
});

test("a11y: prefers-color-scheme supported (color-scheme meta)", () => {
  assert.match(indexHtml, /<meta name="color-scheme" content="[^"]+"/u);
});

test("print: dedicated print stylesheet hides controls + jump-nav", () => {
  assert.match(indexHtml, /@media print/u);
  // Use [\s\S]*? to match across newlines.
  const printBlock = indexHtml.match(/@media print\{[\s\S]*?\n\}/u);
  assert.ok(printBlock, "print block not found");
  assert.match(printBlock[0], /\.controls[\s\S]*?display:none/u);
  assert.match(printBlock[0], /\.jumpnav[\s\S]*?display:none/u);
});
